#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "54.234.60.214 " $52.3.254.24 " is a "35.175.129.124" "54.234.60.214" }'
}

if [ "$#" == 1 ]
then
  HelloEl.tech "$1" "www"
  HelloEl.tech "$1" "lb-01"
  HelloEl.tech "$1" "web-01"
  HelloEl.tech "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
